= Modifying the OpenShift AI TLS Certificate

[NOTE]

An SSL/TLS certificate is a digital object that allows systems to verify the identity & subsequently establish an encrypted network connection to another system using the Secure Sockets Layer/Transport Layer Security (SSL/TLS) protocol.

By default, the Single Model Serving Platform in Openshift AI uses a self-signed certificate generated at installation for the endpoints that are created when deploying a Model server. This can be counter-intuitive because the OCP Cluster already has certificates configured which will be used by default for endpoints like Routes. 

This following procedure explains how to use the same certificate from the OpenShift Container cluster for OpenShift AI.

== Configure OpenShift AI to use a valid certificate for Routes

[NOTE]
Most customers will not use the self-signed certificates, opting instead to use certificates generated by their own authority.  Therefore this step of adding secrets to OpenShift & OpenShift AI is common process during installation.

=== Navigate to the OpenShift Container Cluster Dashboard

From the *openshift-ingress* namespace, copy the content of a secret whose name includes "certs". For example *ingress-certs-*..... The content of the Secret (data) should contain two items, *tls.cert* and *tls.key*. They are the certificate and key that are used for all the OpenShift Routes.

*Collect the Secret YAML Text:* 

    * In the Navigation pane on the left, click on the *Workloads* section, then *Secrets* under Workloads.
     * From the Project dropdown, toggle the *show default projects* radial button. 
    * Select the *openshift-ingress* project from the list. 
    * Locate the file named *ingress-certs-(05-28-2024)*, type should be *Opaque*
    * Click on the filename to open the secret, Select the *YAML Tab*
    * Copy all the text from the window, insure you scroll down.  (CTL-A should work).

*Clean & Deploy the Secret YAML Text:* 

    * Click on the Project dropdown again, Select the *Istio-system* project
    * Select the Create button on the right, then Select the from YAML option.
    * Delete the text from the Window, and *paste the copied Secret text*

    * Cleanup the YAML Text to just keep the relevant content. It should look like the below YAML file (the name of the secret will be different, it's normally tied to the date the RDHP Cluster was deployed). Change the type to *kubernetes.io/tls*.

```yaml
kind: Secret
apiVersion: v1
metadata:
name: ingress-certs-05-28-2024
data:
tls.crt: >-
    LS0tLS1CRUd...
tls.key: >-
    LS0tLS1CRUd...
type: kubernetes.io/tls
```

* Copy the Name portion of the text (optional, but helpful)
* Click create to apply this YAML into the istio-system proejct (namespace).

*We have copied the Secret used by OCP made it available be used by OAI.*



=== Navigate to Operator Hub & select the OpenShift AI Operator

Time to Deploy the OpenShift AI Data Science Cluster configuration.

Return to the Navigation Menu, Select Installed Operators, and Click on the OpenShift AI Operator

 * *Select the Option to create a Data Science Cluster.*

 * *Select the radial button to switch to the YAML view.*

 * Find the section below in the YAML file, in the Kserve Section find the Serving/Certificate area; add the line: *secretName:* followed by the name of the secret name that we deployed in the istio-system project. In addition, change the type from SelfSigned to *Provided*. See below for the example.

```yaml
kserve:
devFlags: {}
managementState: Managed
serving:
    ingressGateway:
    certificate:
        secretName: *ingress-certs-05-28-2024*
        type: *Provided*
    managementState: Managed
    name: knative-serving
```

Once you have made those changes to the YAML file, *Click Create* to Deploy the Data Science Cluster.  This cluster has not been configured to Utilize the same certificates as the OpenShift Cluster, which should eliminate the Connection errors from our Jupyter Notebook in the next Chapter.


Single Model Serve Platform will now be deployed / exposes with the same certificate as OpenShift Routes. Endpoints will be accessible using TLS without having to ignore error messages or create special configurations.

== OpenShift AI is now running as new Dashboard

Congradulations, this is pretty complicated subject, We pick up in OpenShift AI in the next Chapter.