= Installing Red{nbsp}Hat OpenShift AI Using the Web Console

*Red{nbsp}Hat OpenShift AI* is available as an operator via the OpenShift Operator Hub.  You will install the *Red{nbsp}Hat OpenShift AI operator* and dependencies using the OpenShift web console in this section.

== Lab: Installation of Red{nbsp}Hat OpenShift AI

IMPORTANT: The installation requires a user with the _cluster-admin_ role

. Login to the Red Hat OpenShift using a user which has the _cluster-admin_ role assigned.

. Navigate to **Operators** -> **OperatorHub** and search for each of the following Operators individually.  Click on the button or tile for each. In the pop up window that opens, ensure you select the latest version in the *stable* channel and click on **Install** to open the operator's installation view. For this lab you can skip the installation of the optional operators

[*] You do not have to wait for the previous Operator to complete before installing the next. For this lab you can skip the installation of the optional operators as there is no GPU.

    * Web Terminal 

    * Red Hat OpenShift Serverless 

    * Red Hat OpenShift Service Mesh

    * Red Hat OpenShift Pipelines 

    * GPU Support

    **  Node Feature Discovery Operator (optional)

    **  NVIDIA GPU Operator (optional)

[TIP]
 
 Installing these Operators prior to the installation of the OpenShift AI Operator in my experience has made a difference in OpenShift AI acknowledging the availability of these components and adjusting the initial configuration to shift management of these components to OpenShift AI. 

. Navigate to **Operators** -> **OperatorHub** and search for *OpenShift AI*.

. Click on the `Red{nbsp}Hat OpenShift AI` operator. In the pop up window that opens, ensure you select the latest version in the *stable* channel and click on **Install** to open the operator's installation view.
+

. In the `Install Operator` page, leave all of the options as default and click on the *Install* button to start the installation.

. The operator Installation progress window will pop up. The installation may take a couple of minutes.


WARNING: Do proceed with the installation past this point.  In order to access the LLM remotely; There will be some modifcations to the Data Science Cluster YAML file prior to completing the installation of Red Hat OpenShift AI.   