= Red Hat OpenShift AI

== Kubernetes & OpenShift

OpenShift builds upon Kubernetes by providing an enhanced platform with additional capabilities. It simplifies the deployment and management of Kubernetes clusters while adding enterprise features, developer tools, and security enhancements.

In addition, Openshift provides a Graphic User Interface for Kubernetes. Openshift AI runs on Openshift; therefore, the engine under the hood of both products is Kubernetes.  

Most workloads are deployed in kubernetes via YAML files. A Kubernetes  YAML manifest file is a configuration file written in YAML (YAML Ain't Markup Language) that defines the desired state of a Kubernetes deployment. These YAML files are used to create, update, or delete deployments in Kubernetes / OpenShift clusters.

Don’t worry about needing to know how to write these files. That's what OpenShift & OpenShift AI will take care of for us.  In this course,  we will just need to select the options we want in the UI. OpenShift and OpenShift AI will take care of creating the YAML deployment files. 

We will have to perform a few YAML file copy-and-paste operations; instructions are provided in the course. 

Just know, YAML files create resources directly in the Kubernetes platform. We primarily use the OpenShift AI UI to perform these tasks to deliver our LLM.